#!/bin/sh

### BEGIN INIT INFO
# Provides:          react-micro-frontend
# Required-Start:    $local_fs $remote_fs $network $syslog $named $time
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the react-micro-frontend
# Description:       starts react-micro-frontend using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/local/bin/react-micro-frontend-server-go
DAEMON_OPTS="-RMF_LISTEN_ADDRESS=127.0.0.1:8080 -RMF_STARTUP_INIT_DIR=/opt/react-micro-frontend -RMF_SERVE_STATIC_FILES=false"
#CFG_DIR=/etc/react-micro-frontend
NAME=react-micro-frontend
DESC=react-micro-frontend
USER=react-micro-frontend
GROUP=react-micro-frontend

# make config dir
#[ -d $CFG_DIR ] || mkdir $CFG_DIR

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions


case "$1" in
	start)
		echo -n "Starting $DESC: "
		start-stop-daemon --start --quiet --background \
            --make-pidfile --pidfile /var/run/$NAME.pid \
            --chuid $USER  --user $USER  --group $GROUP \
            --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
            --user $USER --exec $DAEMON || true
		echo "$NAME."
		;;

	restart)
		echo -n "Restarting $DESC: "
		start-stop-daemon --stop --quiet --pidfile  /var/run/$NAME.pid \
            --user $USER --exec $DAEMON || true
		sleep 1
		start-stop-daemon --start --quiet --background \
            --make-pidfile --pidfile  /var/run/$NAME.pid \
            --chuid $USER  --user $USER  --group $GROUP \
            --exec $DAEMON -- $DAEMON_OPTS || true
		echo "$NAME."
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" $DESC && exit 0 || exit $?
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|status}" >&2
		exit 1
		;;
esac

exit 0
